name:  ranger-windows
title:  Ranger (Windows)
version: "1.0"
summary:  You are a space pilot hired to rescue pilots imprisoned on an alien planet
description: |
  You are a space pilot hired to rescue pilots imprisoned on an alien planet. After landing you can pickup a few weapons and a medikit from your spaceship, then move through the door to confront the aliens! The prisoner can be found in a prison to the North. Press F to tell him to wait, press F again to make him follow you, back to your spaceship. Use the keyboard (W,A,S,D) to move, and use the mouse to look around and fire your weapons. Select your current weapon using the number keys, or the mouse wheel. When hit you can receive up to three wounds, slowing you down. Using a medikit (M) will heal all wounds you currently have. After every mission, a more dangerous mission begins. If you rescued the prisoner, extra ammo will be available at the start of the next mission.

grade: stable
icon: ranger_icon.png

base: core18
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko
  SOMMELIER_STRICT: "1"                                    # Make Sommelier exit when unset variable is used. (useful to find bugs in sommelier)

apps:
  ranger:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "ranger.exe"
      #INSTALL_EXE: "$SNAP/Blockout25_setup.exe"
      #INSTALL_FLAGS: "/S"
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
 # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  installer:
    plugin: dump
    source: ./

  # The sommelier script helps you snap Windows applications using Wine. It 
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git

# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable

